server:
  port: 8080

jwt:
  secret_key: "wvu6KYaxw0AWYCIzm2B4vCYU8Er2X0yvQQD7Yz1y58Y="
  expiration: 86400000 # 1일 (밀리초)
  audience: "order-service"

spring:
  datasource:
    url: jdbc:h2:mem:jwt;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect